include(CMakeFindDependencyMacro)
list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})

list(REMOVE_AT CMAKE_MODULE_PATH -1)

FIND_PACKAGE(Poco REQUIRED Net)
FIND_PACKAGE(jsoncpp REQUIRED)
FIND_PACKAGE(CURLPP REQUIRED curlpp)
FIND_PACKAGE(Boost 1.73 COMPONENTS log log_setup filesystem REQUIRED)
find_package(RapidJSON REQUIRED)
add_definitions(-DBOOST_LOG_DYN_LINK)

include("${CMAKE_CURRENT_LIST_DIR}/NEVONEX-FCAL-PLATFORMTargets.cmake")
